name = "porfolio"
compatibility_date = "2025-09-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/cloudflare-pages-build"

# R2 binding cho incremental cache
[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "vuong-portfolio-cache"